git-svn-id: https://homeunix.googlecode.com/svn/trunk@97 fc8433b4-f986-8c03-71af-1d9c613bc296

diff --git a/src/opt/bin/unique b/src/opt/bin/unique
--- a/src/opt/bin/unique
+++ b/src/opt/bin/unique
@@ -1,5 +1,10 @@
 #!/usr/bin/env bash
 
+md5(){
+	md5sum "$@" | awk '{print $1}'
+}
+
+
 #rm -rf /var/tmp/uniq
 
 set -o pipefail
@@ -13,41 +18,55 @@ startdir="`pwd`"
 
 _d=`date "+%Y%m%d_%H%M"`
 
-find . -d -type d -not -name 'DUPLES' \
+find -L . -d -type d -not -name 'DUPLES' \
 | while read d; do
 	cd "$startdir"
 	cd "$d"
 	(( ++weight ))
 	_w=`printf "%04d" $weight`
-	dirhash=`find . -maxdepth 1 -mindepth 1 -type f -name '?*.???' -ls | grep -iE '[^\.]\.[a-z][^\.]{2}$' | { read x || exit 1; echo "$x"; cat; } | md5` || continue
+	dirhash=`find . -maxdepth 1 -mindepth 1 -type f -name '?*.???' -not -name 'DUPLE*' -ls | grep -iE '[^\.]\.[a-z][^\.]{2}$' | { read x || exit 1; echo "$x"; cat; } | md5` || continue
 	if [ -z "$dirhash" ]; then
 		echo "Dirhash is empty. Exiting."
 		exit 1
 	fi		
 	list="$dir/$dirhash"
+	echo "list: $list" 1>&2
 	_pwd=`pwd | sed -r 's/\//\\\\\//g'`
 	if [ ! -f "$list" ]; then
-		count=`ls -d ?*.??? | grep -iE '[^\.]\.[a-z][^\.]{2}$' | wc -l`
+		count=`ls -d ?*.??? | grep -vE '^DUPLE' | grep -iE '[^\.]\.[a-z][^\.]{2}$' | wc -l`
 		echo -n -e "Processing directory \e[31m$PWD\e[0m "
 		printf "(%d files) " "$count"
-		ls -d ?*.??? | grep -iE '[^\.]\.[a-z][^\.]{2}$' | fastsum - | sed -r "s/^([^ ]+) +(.*)/\1 :$_pwd\\/\2/"  | tee "$list" | while read x; do
+		ls -d ?*.??? | grep -vE '^DUPLE' | grep -iE '[^\.]\.[a-z][^\.]{2}$' | fastsum - | sed -r "s/^([^ ]+) +(.*)/\1 :$_pwd\\/\2/"  | tee "$list" | while read x; do
 			if (( ++n % 20 == 0 )); then echo -n "$n"; elif (( n % 2 == 0 )); then echo -n '.'; fi
 		done		
 		cat "$list" | sed -r "s/[0-9]*:/$_d:/"  >> ~/db/uniq.db
 		echo "DONE"
 	fi 1>&2		
-	cat "$list" | sed -r "s/[0-9]*:/$_w:/"
+	cat "$list" | grep -v 'DUPLE' | sed -r "s/[0-9]*:/$_w:/"
 done \
 | sort | while read x; do
 	hash="${x%% *}"
 	file="${x#*:}"
 	if [ "$hash" = "$last_hash" ]; then
-		echo "Duplicate: $file" >&2
-		if [ ! -d "$startdir/DUPLES" ]; then mkdir "$startdir/DUPLES"; fi
-		newname="${file##*/}"
-		if [ -f "$startdir/DUPLES/$newname" ]; then newname="$((RANDOM + 10000))$newname"; fi
-		if [ -f "$startdir/DUPLES/$newname" ]; then newname="$((RANDOM + 10000))$newname"; fi
-		mv "$file" "$startdir/DUPLES/$newname"
+		dir=`dirname "$file"`
+		base=`basename "$file"`
+		n="${file}"
+		n="${n##*/}"
+		n="${n%%:ss*}"
+		echo "Duplicate: $n" >&2
+		
+		if [ ! -d "$dir/DUPLES" ]; then
+			mkdir "$dir/DUPLES" || { echo "Cannot create dir $dir/DUPLES. Exiting."; exit 1; }
+		fi
+		
+		newname="$dir/DUPLES/$base"
+		
+		if [ -f "$newname" ]; then
+			echo "Destination exists. Skip moving."
+		else
+			mv "$file" "$newname"
+		fi
+				
 	else
 		last_hash="$hash"
 		last_file="$file"		
@@ -55,6 +74,8 @@ done \
 done
 
 
+
+#find -L . -type f -name 'DUPLE.*'
 
 
 
